# Generated by Django 5.1.15 on 2026-04-28 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Demo Site', max_length=100)),
                ('contact_email', models.EmailField(default='hello@example.com', max_length=254)),
                ('default_seo_description', models.TextField(blank=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
            ],
            options={
                'verbose_name': 'Site configuration',
                'verbose_name_plural': 'Site configuration',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('label', models.CharField(max_length=80)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('is_external', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('parent', 'order'), name='menuitem_parent_order_uniq')],
            },
        ),
    ]
